import type { Metadata } from "next";
import { ToastProvider, ThemeProvider } from "@/context";
import { ToastContainer } from "@/components";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactNode } from "react";
import { createDBConnection } from "@/lib";
import "./styles/globals.css";

const geistSans = Geist({
  variable: "--font-primary",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-secondary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Курси фронтенду",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  let isDatabaseConnected: boolean = false;
  isDatabaseConnected = await createDBConnection();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider>
          <ToastProvider>
            {isDatabaseConnected ? children : null}
            <ToastContainer />
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
