import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import { ToastProvider, ThemeProvider, UserProvider } from "@/context";
import { ToastContainer, Header } from "@/components";
import { ReactNode } from "react";
import { createDBConnection } from "@/lib";
import "./styles/globals.css";

const taktikaFont = localFont({
  src: [
    {
      path: "../../public/fonts/Taktika/TaktikaSans-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Taktika/TaktikaSans-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Taktika/TaktikaSans-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Taktika/TaktikaSans-Demi.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/Taktika/TaktikaSans-Heavy.otf",
      weight: "900",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-taktika",
});

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Курси фронтенду",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  let isDatabaseConnected: boolean = false;
  isDatabaseConnected = await createDBConnection();

  return (
    <html lang="en">
      <body className={`${taktikaFont.variable} ${interFont.variable}`}>
        <ThemeProvider>
          <ToastProvider>
            <UserProvider>
              <Header />
              {isDatabaseConnected ? children : null}
            </UserProvider>
            <ToastContainer />
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
