import type { Metadata } from "next";
import { UserProvider, ToastProvider, GlobalProvider } from "./context";
import ToastContainer from "./components/Toast";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Курси фронтенду",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GlobalProvider>
          <ToastProvider>
            <UserProvider>
              {children}
              <ToastContainer />
            </UserProvider>
          </ToastProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
